name: dart_cca_example
version: 0.0.1
dependencies:
  angular: ">=0.11.0 <0.12.0"
  browser: any
  chrome: any
  js: any
  shadow_dom: any
  echo_v1_api:
    path: submodule/dart_echo_v1_api_client
dev_dependencies:
  unittest: any
