name: timecard_client
version: 0.0.1
dependencies:
  angular: ">=0.10.0 <0.11.0"
  angular_ui: ">=0.3.0 <0.4.0"
  browser: any
  chrome: any
  js: any
  shadow_dom: any
  timecard_dev_api:
    path: submodule/dart_timecard_dev_api_client
dev_dependencies:
  unittest: any
transformers:
- chrome
